version: '3.8'

services:
  traffic_forecast:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=monitor
      - POSTGRES_PASSWORD=forecast2022
      - POSTGRES_DB=traffic-forecast
      - SECRET_KEY=upct2022_sk
      - FASTAPI_CONFIG=development
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - db
      - adminer

  db:
    image: postgres:13
    expose:
      - 5432
    environment:
      - POSTGRES_USER=monitor
      - POSTGRES_PASSWORD=forecast2022
      - POSTGRES_DB=traffic-forecast
    volumes:
      - ./data/postgres_db:/var/lib/postgressql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

  influxdb:
    image: influxdb:latest
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb2:rw
#    environment:
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=admin
#      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
#      - DOCKER_INFLUXDB_INIT_ORG=e-lighthouse
#      - DOCKER_INFLUXDB_INIT_BUCKET=test-bucket
    ports:
      - 8086:8086
