openapi: "3.0.3"
info:
  title: "Traffic Forecast"
  description: "Microservice app that enables the possibility to create a network, add monitored interfaces and add traffic to an especified interface. With the monitored interfaces info, we can perform a forecast."
  version: "1.0"
servers:
 - url: "https://localhost:5000/"
   description: Local server for testing
paths:
  /network:
    get:
      summary: Returns a list of networks
      description: Returns a list of networks by ID
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /interface:
    get:
      summary: Return a list of interfaces
      description: Returns a list of interfaces given a network ID
      responses:
        '200':
          description: A JSON array of interfaces
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string